name: absen
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  shared_preferences: ^2.2.2
  geolocator: ^11.0.0
  image_picker: ^1.1.0
  path_provider: ^2.1.3
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  camera: ^0.10.0+4
  intl: ^0.18.1
  path: ^1.8.3
  encrypt: ^5.0.1
  flutter_image_compress: ^2.1.0
  image: ^4.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/top_wave.png
